DROP DATABASE db_project2;

-- MySQL Script generated by MySQL Workbench
-- mer. 23 oct. 2019 17:40:42 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_project2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_project2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_project2` DEFAULT CHARACTER SET utf8 ;
USE `db_project2` ;

-- -----------------------------------------------------
-- Table `db_project2`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`user` (
  `id` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` TEXT NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project2`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `category_id_category` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id_category`),
  INDEX `fk_categories_categories1_idx` (`category_id_category` ASC),
  CONSTRAINT `fk_categories_categories1`
    FOREIGN KEY (`category_id_category`)
    REFERENCES `db_project2`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project2`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`brand` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project2`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`color` (
  `id` INT NOT NULL,
  `color_hexa` VARCHAR(6) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project2`.`size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`size` (
  `id`  NOT NULL,
  `size_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_project2`.`reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`reference` (
  `id` INT NOT NULL,
  `sku_reference` INT NOT NULL,
  `color_id` INT NOT NULL,
  `size_id`  NOT NULL,
  PRIMARY KEY (`id`, `color_id`, `size_id`),
  INDEX `fk_reference_color1_idx` (`color_id` ASC),
  INDEX `fk_reference_size1_idx` (`size_id` ASC),
  CONSTRAINT `fk_reference_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `db_project2`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reference_size1`
    FOREIGN KEY (`size_id`)
    REFERENCES `db_project2`.`size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project2`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`article` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `category_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  `reference_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`, `brand_id`, `reference_id`),
  INDEX `fk_article_category1_idx` (`category_id` ASC),
  INDEX `fk_article_brand1_idx` (`brand_id` ASC),
  INDEX `fk_article_reference1_idx` (`reference_id` ASC),
  CONSTRAINT `fk_article_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `db_project2`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `db_project2`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_reference1`
    FOREIGN KEY (`reference_id`)
    REFERENCES `db_project2`.`reference` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project2`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`payments` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project2`.`shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`shipment` (
  `id` INT NOT NULL,
  `delivery_time` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project2`.`facturation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`facturation` (
  `id` INT NOT NULL,
  `number` INT NULL,
  `payments_id` INT NOT NULL,
  `shipment_id` INT NOT NULL,
  `checkout` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`, `payments_id`, `shipment_id`),
  INDEX `fk_facturation_payments1_idx` (`payments_id` ASC),
  INDEX `fk_facturation_shipment1_idx` (`shipment_id` ASC),
  CONSTRAINT `fk_facturation_payments1`
    FOREIGN KEY (`payments_id`)
    REFERENCES `db_project2`.`payments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturation_shipment1`
    FOREIGN KEY (`shipment_id`)
    REFERENCES `db_project2`.`shipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project2`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`cart` (
  `id` INT NOT NULL,
  `facturation_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `date` INT NOT NULL,
  PRIMARY KEY (`id`, `facturation_id`, `user_id`),
  INDEX `fk_cart_facturation1_idx` (`facturation_id` ASC),
  INDEX `fk_cart_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_cart_facturation1`
    FOREIGN KEY (`facturation_id`)
    REFERENCES `db_project2`.`facturation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_project2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project2`.`cartArticle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`cartArticle` (
  `cart_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  `quantity` INT NULL,
  `id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cart_id`, `article_id`, `id`),
  INDEX `fk_cart_has_article_article1_idx` (`article_id` ASC),
  INDEX `fk_cart_has_article_cart1_idx` (`cart_id` ASC),
  CONSTRAINT `fk_cart_has_article_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `db_project2`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_has_article_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `db_project2`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project2`.`date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project2`.`date` (
  `id` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateCart` DATE NOT NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
